spring:
  application:
    name: BookStack
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    location: classpath:db/migration

  dotenv:
    enabled: true
    path: .env
    priority: high
    fail-on-missing: false

  jwt:
    secret: ${JWT_SECRET_KEY}
    issuer: ${JWT_TOKEN_ISSUER}
